# Generated by Django 4.0.1 on 2022-04-04 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_recipe_created_by_recipe_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredients',
            field=models.ManyToManyField(to='meals.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
