# Generated by Django 4.0.1 on 2022-04-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='meals.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
