# Generated by Django 4.0.1 on 2022-04-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', to='meals.RecipeIngredient'),
        ),
    ]
