# Generated by Django 4.0.1 on 2022-04-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_remove_recipe_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ManyToManyField(related_name='ingredients', to='meals.RecipeIngredient'),
        ),
    ]
