# Generated by Django 4.0.1 on 2022-04-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_remove_recipe_ingredients_recipeingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ManyToManyField(related_name='ingredients', to='meals.Recipe'),
        ),
    ]
