# Generated by Django 4.0.1 on 2022-04-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_remove_recipeingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('created_by', 'name')},
        ),
    ]
