# Generated by Django 4.0.1 on 2022-04-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='ingredients',
            new_name='meals',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='recipes',
            new_name='shoppingList',
        ),
    ]
